Adding the sensors and location compatibility
evrythng/epcis2.0-to-evrythng pull request #10
Opened 2020-09-29 11:03 UTC by clementh59

2020-10-09 10:26 UTC, joelvogt requested changes

2020-10-09 10:26 UTC, joelvogt commented on evrythng-proxy/EpcisEvent/epcisEvents.js
> +    throw Error(`More than one entry found for ${epc}`);
Javascript also requires the new operator to create instances: throw new Error(`More...`)

2020-10-09 10:26 UTC, joelvogt commented on evrythng-proxy/EpcisEvent/epcisEvents.js
> +    throw Error('Some thngs already exist. They cannot be added twice');
Same here, the new operator is missing

2020-10-09 10:26 UTC, joelvogt commented on evrythng-proxy/EpcisEvent/epcisEvents.js
> +        throw Error(`Invalid EPC  because product ${gtin} does not exist.`);
new Error

2020-10-09 10:26 UTC, joelvogt commented on evrythng-proxy/EpcisEvent/epcisEvents.js
> +    throw Error('Could not find all the EPCs specified in the event');
new Error

2020-10-09 10:26 UTC, joelvogt commented on evrythng-proxy/EpcisEvent/epcisEvents.js
> +        throw Error(`Invalid EPC  because product ${gtin} does not exist.`);
new Error

2020-10-09 10:26 UTC, joelvogt commented on evrythng-proxy/EpcisEvent/epcisEvents.js
> +    throw Error('Could not find all the EPCs specified in the event');
new Error

2020-10-09 10:26 UTC, joelvogt commented on evrythng-proxy/EpcisEvent/epcisEvents.js
> +  /* eslint-enable require-jsdoc */
Isn't jsdoc required by default?

2020-10-09 13:00 UTC, clementh59 commented on evrythng-proxy/EpcisEvent/epcisEvents.js
> +  /* eslint-enable require-jsdoc */
Yes but I disabled it here : https://github.com/evrythng/epcis2.0-to-evrythng/blob/clementHecquet-patch/evrythng-proxy/EpcisEvent/epcisEvents.js#L448

2020-10-09 13:08 UTC, clementh59 commented on evrythng-proxy/EpcisEvent/epcisEvents.js
> +  /* eslint-enable require-jsdoc */
Yes but I desibaled it here https://github.com/evrythng/epcis2.0-to-evrythng/blob/clementHecquet-patch/evrythng-proxy/EpcisEvent/epcisEvents.js#L442

2020-10-15 14:47 UTC, joelvogt approved these changes

2020-10-15 14:54 UTC, merged